spring:
  application:
    name: bank-api

  datasource:
    url: jdbc:mysql://localhost:3306/meu_banco?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

    jpa:
      hibernate:
        ddl-auto: validate
      show-sql: false
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
          format_sql: true
jwt:
  secret: password
  expiration: 86400000

external:
  util-api:
    base-url: https://util.devi.tools/api